modif jenkinsfile

diff --git a/CRUD/Jenkinsfile b/CRUD/Jenkinsfile
--- a/CRUD/Jenkinsfile
+++ b/CRUD/Jenkinsfile
@@ -2,7 +2,7 @@ pipeline {
     agent any
 
     environment {
-        DOCKER_IMAGE = 'votre-dockerhub-username/crm-symfony'
+        DOCKER_IMAGE = 'eljemlihoussam/crm-symfony'
         DOCKER_TAG = "${BUILD_NUMBER}"
         SONAR_TOKEN = credentials('sonarqube-token')
     }
@@ -11,6 +11,25 @@ pipeline {
         stage('Checkout') {
             steps {
                 checkout scm
+            }
+        }
+
+        stage('Install Composer') {
+            steps {
+                sh '''
+                    EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+                    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+                    ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+                    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+                        >&2 echo 'ERROR: Invalid installer signature'
+                        rm composer-setup.php
+                        exit 1
+                    fi
+
+                    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
+                    rm composer-setup.php
+                '''
             }
         }
 
@@ -62,8 +81,8 @@ pipeline {
                     playbook: 'deploy.yml',
                     inventory: 'inventory.ini',
                     extras: [
-                        'docker_image=${DOCKER_IMAGE}',
-                        'docker_tag=${DOCKER_TAG}'
+                        "docker_image=${DOCKER_IMAGE}",
+                        "docker_tag=${DOCKER_TAG}"
                     ]
                 )
             }
@@ -81,4 +100,4 @@ pipeline {
             echo 'Pipeline failed!'
         }
     }
-} 
+}
